#!/bin/bash
if [[ ! -d build ]] ; then
   mkdir build
fi

pushd build
cmake -G Xcode -Wno-dev .. -DwxWidgets_CONFIG_EXECUTABLE=/Users/davec/Dev/wxWidgets-staticlib/bin/wx-config -DCMAKE_BUILD_TYPE=Release -DBUNDLE_APP=1 -DCPACK_BINARY_DRAGNDROP=1 -DSoapySDR_DIR=/usr/local/share/cmake/SoapySDR/
popd
